name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./dotnet-project
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./dotnet-project

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: ./dotnet-project
      
    - name: Publish
      run: dotnet publish DotNetCicdDemo.Api/DotNetCicdDemo.Api.csproj -c Release -o ./publish
      working-directory: ./dotnet-project
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-api-app
        path: dotnet-api-app
        retention-days: 1
